### ISSUE TITLE
Download button for users and admin

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#139]
- [x] make a download button for everyone on the main page

After clicking this, you get to the download page.
For people with 'tagger' role:
- [x] There should be a 1-click button that just instantly downloads all the data for the images you have labeled (as a `csv`). so every field.
- [x] There is also a table that allows for users to make decisions: such as what catalog, what, attributes, etc. The table can potentially reuse something already existing from @ShahNafisRafique 

For people with 'admin' role:
- [x] The 1-click button should instantly download all the data (as a `csv`).

@kaveritakkellapati — i think the first thing to do is the 1 click buttons (for 'admin' and 'tagger'). after that, the table for more fine-grained decisions. does this make sense?

@ShahNafisRafique, @somyamohanty  — any other comments?

**Comment by ShahNafisRafique** [comment]
The 1 click button for admin/tagger roles seems easy to do. 

For downloading specific catalogs a user is part of and the archives of those catalogs that also seems easy to do. 

The part that I think might be hard is being able to select by the fields like washover/no washover due to the wide range of possible fields, but still possible to do.

**Comment by ebgoldstein** [comment]
good points @ShahNafisRafique...
ok, so that I think that should define the implementation order for @kaveritakkellapati :

1. 1-click button for 'taggers' to download all their data.
2. an additional 1-click button for 'admins' to download all data
3. a way for 'taggers' and admin to download subsets of their data: based specific catalogs/archives, like the table a use sees when they log in
4. a more complicated way for taggers to download specific fields from catalogs/archives

**Comment by ebgoldstein** [comment]
(we had an old download issue - #111 - that was opened by @dbuscombe-usgs.. just as an FYI.. i forgot about it until a moment ago. So i'm sorry for not keeping a single thread.... I think we are addressing all of the concerns from that earlier issue.. but i wanted to loop him in in case he has any concerns/comments/suggestions)

**Comment by ebgoldstein** [comment]
so for the 1-click button, the columns are: 
ImageID, 
image name, 
User ID, 
Catalog ID, 
catalog name, 
archive ID, 
archive name,   
and then a bunch of colums that are all the tags,

**Comment by ShahNafisRafique** [comment]
how to make csv 
https://code-maven.com/create-and-download-csv-with-javascript
thx google

**Comment by ebgoldstein** [comment]
hey @ShahNafisRafique , can you post the info for @kaveritakkellapati regarding the `...` notation for unnesting the `tag` column of the json into separate columns

**Comment by ShahNafisRafique** [comment]
Yes sure.
The header should have all the tags across all the question set. For example given the tags 

```js
const tag1 = {
    imageId:'id1',
    userId:'user1',
    tag: {
        sand:true,
        ocean:false
    }
};

const tag2 = {
    imageId:'id2',
    userId:'user2',
    tag: {
        mountain:'tall',
        snowy:false
    }
};

```

The header of the csv + the data from those 2 tags above is

| imageId | userId | sand      | ocean     | mountain  | snowy     |
|---------|--------|-----------|-----------|-----------|-----------|
| id1     | user1  | true      | false     | undefined | undefined |
| id2     | user2  | undefined | undefined | 'tall'    | false     |

As you can see, the row for `tag1` has the last two columns `undefined` because those columns dont exist in that tag, and likewise for `tag2`.

The the 1st task is to create a list of the tag columns, you can do something like this
```js
const tag1Header = Object.keys(tag1.tag)
const tag2Header = Object.keys(tag2.tag)
const allHeaders = [...tag1Header,...tag2Header]
```
Which results in `[ 'sand', 'ocean', 'mountain', 'snowy' ]` 

Where `...` comes useful is how it kind of flattens out whatever value.

For example
```
[tag1Header,tag2Header] = [['sand','ocean'],['mountain','snowy']]
[...tag1Header,...tag2Header] = ['sand', 'ocean', 'mountain', 'snowy']
```

With this array now, you can iterate over all the tags, for each tag get the value of that header (sand,ocean,mountain) and push that value to an array to preserve the order. In the end you should get something like so

```
[ 'sand', 'ocean', 'mountain', 'snowy' ]
[ 'id1', 'user1', true, false, undefined, undefined ]  
[ 'id2', 'user2', undefined, undefined, 'tall', false ]
```
@kaveritakkellapati does this make sense?
and @ebgoldstein is this too much 😆.

**Comment by ebgoldstein** [comment]
(Once this is integrated we should do a new tagged release)

**Comment by ebgoldstein** [comment]
ok, cool i see https://github.com/UNCG-DAISY/Coastal-Image-Labeler/commit/e3957f0841aa9814e94108612eaa223849a734f1 and i see on the dev server that there is a button for users and admin and that both work — i could download csv's! very awesome @kaveritakkellapati !

However, I see from these lines in `export.tsx` that the specific tags to export are hard coded:
https://github.com/UNCG-DAISY/Coastal-Image-Labeler/blob/e3957f0841aa9814e94108612eaa223849a734f1/src/dashboard/src/pages/auth/export.tsx#L120-L135
 
We definitely want to export every single tag for each image. For example, I anticipate in the future there will be other new questions we ask, so export needs to be dynamic, and export answers to every questions. Even now, some of the tags are missing — for example, some images get labeled all water, which means that all the tags are empty except `tags.water == True`. And people might leave comments so their might be data a string in  `tags. Additional Comment`.

for many images, columsn will be empty (i.e., for most images tags.water will be empty/null/NaN).. that's fine.

**Comment by ebgoldstein** [comment]
to clarify, it's ok if some fields are hard coded (correct me if i you think I am wrong @ShahNafisRafique, or if you have a better idea).. such as these: 
```
     'userId', 
     'imageId', 
     'image.name', 
     'catalogId', 
     'catalog.name', 
     'archiveId', 
     'archive.name', 
     'date',
```
 but the tags need to be dynamic.. @kaveritakkellapati — look at @ShahNafisRafique 's comment above in this issue for his ideas of how to do this..

**Comment by ebgoldstein** [comment]
also can we change the buttons to say:
'Export Your Labels' (not 'Export user tags')
'Export All Labels' (not 'Export all tags')

**Comment by ebgoldstein** [comment]
dealing with `tags.water` in https://github.com/UNCG-DAISY/Coastal-Image-Labeler/issues/159

**Comment by ebgoldstein** [comment]
I am going to close this for now, since i have seen a working demo from @kaveritakkellapati
