### ISSUE TITLE
Path: original, compressed, aux?

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#157]
Currently, as i understand it, each image has 2 paths in the DB (original and compressed). When loading in catalog, a user specifies (in the json) a path for the original images and the compressed images. Both original and compressed images also have API endpoints. 

Operating on these images with ML can also lead to derivative products, such as masks/overlays. An example is shown below. This is a mask on top of a NOAA image. 

![image](https://user-images.githubusercontent.com/5330599/94019207-827b1600-fd7f-11ea-8de7-4ea77f49b108.png)

My question is this @ShahNafisRafique : 
Let's say I have a folder on the VM (`datadrive2/auxiliary/`) filled with images like the one above (i.e., a new version of each image). How hard would it be to add an additional path for a given catalog (and also an additional API endpoint), so that one path is the original image, one path is the compressed image, and one path is this new additional/auxiliary image (i.e.., the 3rd panel above). Can i just add a 3rd field in the `path` of the json or a 3rd field in the DB?

**Comment by ebgoldstein** [comment]
I am wondering about this, because showing these GradCAM images to users of the [Storm Impact Map](https://github.com/UNCG-DAISY/StormImpactMap) might be beneficial.. (that use case is here: https://github.com/UNCG-DAISY/StormImpactMap/issues/20).

**Comment by ShahNafisRafique** [comment]
@ebgoldstein You can add a 3rd field to that `path` object, then we can make a new API endpoint that will try to give an image at that path, and fall back to the `path.original` path (since thats the only required one) if it fails.

Not too hard, can be made easily

**Comment by ebgoldstein** [comment]
cool...

- [ ] Make GradCAM for an archive
- [ ] Upload to VM (`datadrive2/aux/<catalog>/`
- [ ] Add catalog via CLI w/ additional path object

**Comment by ShahNafisRafique** [comment]
I added a new endpoint that allows you to specify which path for an image. It follows the format of

```
/api/image/:imageId/:type
```
`imageId` - Would be the MonogDB `_id` of the image, if that image doesnt exist the server will send the error image  
`type` - would be the key for the path, like `compressed`, `original`, `auxiliary`, `blackwhite`, `specialImageThatIsReallyCool` or whatever. If the path created with that key doesnt exist, the server will try to use the `original` path. If that doesnt exist the server will send the error image

Theres a special case with `type` where you can omit it if you just want the `original` path, like
```
/api/image/:imageId
```

Here are some examples with the dev dashboard
[original](https://dev.coastalimagelabeler.science/api/image/5f495830b9a4614ea7911bad/original)
[compressed](https://dev.coastalimagelabeler.science/api/image/5f495830b9a4614ea7911bad/compressed)
[original, without type](https://dev.coastalimagelabeler.science/api/image/5f495830b9a4614ea7911bad)


I didnt remove the current API for getting the image just to not break anything, so whenever you guys can just move to that route and I can remove the old image API. The only additions would you ever need to do would be to edit the `index.d.ts` file and add the possible `type` values just so that TypeScript can have that for typechecking.

**Comment by ebgoldstein** [comment]
So — i have new images (gradcam) for Isaias on the VM — should i delete the Isaias archive and reload it into the DB? Since i need to alter the path entry for each image? recommendations?

**Comment by ShahNafisRafique** [comment]
I dont think you should delete the archives. I think (either with py or nodejs) just update each image.

**Comment by ebgoldstein** [comment]
ok, this is all working now
