### ISSUE TITLE
Table is blinking

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#170]
(for me)...

I labeled all of priority catalog, but then as a test tried to label it again via the button on the drawer.. table is now blinking...

@ShahNafisRafique — you have a reproducible example..

**Comment by ebgoldstein** [comment]
ok, so i assigned a new catalog to myself (Dorian), and the table stopped blinking...

**Comment by ebgoldstein** [comment]
I wonder if this is a remnant of having the old catalog hashes that don;t exits...

**Comment by ShahNafisRafique** [comment]
I think I would like to fix it, because its just a visual glitch

**Comment by ShahNafisRafique** [comment]
Okay so the issue was a visual glitch/faulty logic

When the page first gets loaded, I do a call to the serve saying "Does the user have any assigned images". If that returns true then on the client side it asks for the table data (that takes longer). If not then it shows the "No archive to continue tagging"

The getting the table data part, essentially returns an array of rows, each being a an archive.

This issue comes when there are images that are assigned, but those images belong to catalogs/archives that dont exist, so that row returned is just empty array.

and the page things that because the array is empty, it must mean the API call is still returning the data.

So the fix was to check if the returned row data was `> 0` or not if its less then 0 then that means theres no valid taggable archive left to continue to tag.

**Comment by ShahNafisRafique** [comment]
This only happens if the all the assigned images belong to catalogs/archives/images that dont exist. If one of the assigned images is valid then all is good.

**Comment by ShahNafisRafique** [comment]
@ebgoldstein I dont know if you can any more, but can you check to see if its all fixed. You could go unassign all images from your self and assign a random image with a random catalog ID thats invalid.

**Comment by ebgoldstein** [comment]
Do you want to do this on the dev or production? likely easier on production, as I just unassigned all images to myself on the except 1 image that doesn't exist.

**Comment by ShahNafisRafique** [comment]
I can push the changes to production vm, I just pushed to dev vm

**Comment by ebgoldstein** [comment]
excellent, it works... feel free to close.
