### ISSUE TITLE
long term extensibility

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#38]
Hey @MARDAScience — this dashboard that @ShahNafisRafique is building is mostly for Sallenger regime classification. But what other operations should a Coastal dashboard have? pixel annotation? segmentation? bounding boxes labeling for certain features? i think this would be a good place to have a list... and then also we can figure out what the next steps are... (and have a running list of other data we need to ingest (beyond the NOAA post-storm aerials from [`psi-collect`](https://github.com/UNCG-DAISY/psi-collect)

**Comment by MARDAScience** [comment]
Great! I suppose that ideally it could include polygon labelling, bounding boxes, and pixel annotation would be amazing! I could implement my CRF code that works well for turning sparse into dense (i.e. every pixel) label images. What makes it 'coastal' is the just the data and classes, so you could leverage existing tools. What class labels would be provided? Or is the idea that users could upload their own imagery and classes? Happy to help in any way I can

Here's one idea to make it more 'coastal' - make trained coastal models available. My advice, if you don't already have a specific framework in mind: branch the [maksense.ai code ](https://github.com/SkalskiP/make-sense) because it has all the annotation tools, and is backended by tensorflow-js so can implement CNN models, etc. It would also be nice to implement the CRF model as an option. I could also contribute by training and testing models. Would require knowledge of at least tf-js and npm

**Comment by ebgoldstein** [comment]
these are all good ideas. Once we get v1 deployed, i'll try to parse these, get them rank ordered, and think of a way forward.

**Comment by ebgoldstein** [comment]
Pixel level annotation by leveraging an existing tool? — e.g.,
https://github.com/waoai/react-image-annotate. The key issue is making the manual pixel annotations very lightweight, so it can be stored easily on the mongodb w/o needing a huge db.

**Comment by ebgoldstein** [comment]
I'm closing this... Some of these are wrapped in to evolving long term plans..
