### ISSUE TITLE
remove the tag session ID

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#81]
can you remove the header that says the tag session on the top...  
and also remove the tag session id down near the archive (if you wanted, you could puut the image name there)? 

 <img width="797" alt="Screen Shot 2020-06-09 at 9 56 16 AM" src="https://user-images.githubusercontent.com/5330599/84156482-8b95e080-aa37-11ea-864d-0b647c22809e.png">

**Comment by ShahNafisRafique** [comment]
I can put image id next to the archive name, so it says `archive XXX - Image name` but I would like to have the image td (where it says `Tagging Session: XXX`) just as a way so that if someone ever needs something done on that image we have a unique ID to reference the image by. 

Would it be better to say something like `Tagging Session - Image ID:XXX`?

**Comment by ebgoldstein** [comment]
That is a good point.So:
- keep the tagging session at the top.
- remove tagging session below, and instead have: `Archive: XXXX - Image: YYYY'

**Comment by ShahNafisRafique** [comment]
This is what it is now
![name](https://user-images.githubusercontent.com/38015120/84162608-943de500-aa3e-11ea-83d0-dd33f493f0f7.PNG)

**Comment by ebgoldstein** [comment]
nice, i see it too.
